# Generated by Django 4.0.4 on 2022-05-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('image', models.ImageField(upload_to='blog_img', verbose_name='Portada')),
                ('data', models.TextField(verbose_name='')),
            ],
            options={
                'verbose_name': 'Entrada de blog',
                'verbose_name_plural': 'Entradas del blog',
            },
        ),
    ]
