# Generated by Django 4.0.4 on 2022-05-13 20:39

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import garbanzos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('image', models.ImageField(upload_to='brand_img', verbose_name='Imágen')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Nombre')),
                ('image', models.ImageField(upload_to='car_img', verbose_name='Imágen')),
                ('active', models.BooleanField(verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Imágen para baner',
                'verbose_name_plural': 'Imágenes para baner',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('image', models.ImageField(upload_to='cat_img', verbose_name='Imágen')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
            managers=[
                ('objects', garbanzos.models.CategoryManager()),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('color_code', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('image', models.ImageField(upload_to='prod_img', verbose_name='Imágen')),
            ],
            options={
                'verbose_name': 'Imágen de producto',
                'verbose_name_plural': 'Imágenes de productos',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('shadow', models.CharField(max_length=20)),
                ('birthdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, verbose_name='Título')),
                ('image', models.ImageField(upload_to='prod_img', verbose_name='Imágen')),
                ('detail', models.TextField(verbose_name='Detalles')),
                ('spec', models.TextField(verbose_name='Especificaciones')),
                ('price', models.FloatField(verbose_name='Precio')),
                ('stock', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garbanzos.brand', verbose_name='Marca')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garbanzos.category', verbose_name='Categoría')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garbanzos.color')),
                ('other_images', models.ManyToManyField(blank=True, to='garbanzos.productimages', verbose_name='Otras imágenes')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
            managers=[
                ('objects', garbanzos.models.ProductManager()),
            ],
        ),
    ]
