# Generated by Django 4.0.4 on 2022-06-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbanzos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Texto'),
        ),
    ]
